apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  labels : 
    app : frontend-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend-pod
