apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: proyectosusac/serverbs
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5010