apiVersion: v1
kind: Service
metadata:
  name: backend-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
      name: http
  selector:
    role: backend