apiVersion: v1
kind: Service
metadata:
  name: server
  labels : 
    app : server
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
  selector:
    app: server
