apiVersion: v1
kind: Service
metadata:
  name: backendlb
  labels : 
    app : backendlb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: server
